### ISSUE TITLE
run  make_music_video.py  prompt error at stable_diffusion_pipeline

### ISSUE THREAD

**Issue by eu09** [nateraw/stable-diffusion-videos#108]
python3 make_music_video.py 
Fetching 15 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 69750.07it/s]
You have passed `None` for safety_checker to disable its functionality in <class 'stable_diffusion_videos.stable_diffusion_pipeline.StableDiffusionWalkPipeline'>. Note that this might lead to problems when using <class 'stable_diffusion_videos.stable_diffusion_pipeline.StableDiffusionWalkPipeline'> and is not recommended.
You have disabled the safety checker for <class 'stable_diffusion_videos.stable_diffusion_pipeline.StableDiffusionWalkPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Traceback (most recent call last):
  File "/home/elohlinux/stable-diffusion-videos/examples/make_music_video.py", line 45, in <module>
    pipe.walk(
  File "/home/elohlinux/.local/lib/python3.10/site-packages/stable_diffusion_videos/stable_diffusion_pipeline.py", line 797, in walk
    return make_video_pyav(
  File "/home/elohlinux/.local/lib/python3.10/site-packages/stable_diffusion_videos/stable_diffusion_pipeline.py", line 115, in make_video_pyav
    frames = frames.permute(0, 2, 3, 1)
AttributeError: 'NoneType' object has no attribute 'permute'

**Comment by nateraw** [comment]
Not able to reproduce this error. (see [colab](https://colab.research.google.com/gist/nateraw/c6e8fc936f8bd26ce41f4a5471be30cc/make-music-video-stable-diffusion-test.ipynb) here). In the colab the only thing I changed is `fps=5` so it would generate faster and `batch_size=12` which is the highest batch size my Colab Pro+ machine allowed for.

This error looks like something went wrong with finding the frame files themselves. 

Double check you're on the latest version of the code `pip install --upgrade stable-diffusion-videos[realesrgan]` and try again I guess?

**Comment by Shlok-Bhakta** [comment]
I'm not sure if this will help, I ran into the same issue as I was generating images. My issue was that the amount of interpolation frames was 0 at some point. I was programmatically generating numbers and would sometimes get an array that looked like this [7, 8, 15, 0, 6, 3, 5]. It would always error when generating because of that 0 in index 3. Hope that helps!

**Comment by Yaqing2023** [comment]
The prompt box has a reminder that "Prompts, separated by new line", in my case if i have a prompt with comma ",", it will throw this attribute error; if i remove comma but separate using new line, than it generates video successfully
