### ISSUE TITLE
from stable_diffusion_videos import interface throws error

### ISSUE THREAD

**Issue by Zaithe** [nateraw/stable-diffusion-videos#16]
Whenever i import interface in python it throws the below error
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/home/zaithe/.local/lib/python3.8/site-packages/stable_diffusion_videos/__init__.py", line 75, in __getattr__
    submod = importlib.import_module(submod_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zaithe/.local/lib/python3.8/site-packages/stable_diffusion_videos/app.py", line 6, in <module>
    from .stable_diffusion_walk import SCHEDULERS, pipeline, walk
  File "/home/zaithe/.local/lib/python3.8/site-packages/stable_diffusion_videos/stable_diffusion_walk.py", line 11, in <module>
    pipeline = StableDiffusionPipeline.from_pretrained(
  File "/home/zaithe/.local/lib/python3.8/site-packages/diffusers/pipeline_utils.py", line 154, in from_pretrained
    cached_folder = snapshot_download(
  File "/home/zaithe/.local/lib/python3.8/site-packages/huggingface_hub/_snapshot_download.py", line 182, in snapshot_download
    repo_info = _api.repo_info(
  File "/home/zaithe/.local/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1289, in repo_info
    return self.model_info(
  File "/home/zaithe/.local/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1136, in model_info
    _raise_for_status(r)
  File "/home/zaithe/.local/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 84, in _raise_for_status
    _raise_with_request_id(request)
  File "/home/zaithe/.local/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 95, in _raise_with_request_id
    raise e
  File "/home/zaithe/.local/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 90, in _raise_with_request_id
    request.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/models/CompVis/stable-diffusion-v1-4/revision/main (Request ID: d88ARCfxzZgiWqYtjauWn)
`

**Comment by nateraw** [comment]
Have you authenticated with the Hugging Face Hub?

If in terminal, you can do `huggingface-cli login`.

Or, if you're in a notebook:

```python
from huggingface_hub import notebook_login

notebook_login()
```

**Comment by nateraw** [comment]
Did the fix above work for you?

**Comment by Zaithe** [comment]
@nateraw ,
Apologies got distracted, it looks like that is working now but it says the pytorch installation does not support my video card (3090).
How can i make it use a pytorch installation compatible with my video card?
```
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
```

**Comment by nateraw** [comment]
@Zaithe I'm guessing you have a bad install of torch/cudatoolkit/cuda driver. thus, this is not an issue with this repo. However, the following comment _might_ help you.

https://github.com/nateraw/stable-diffusion-videos/issues/10#issuecomment-1240928499

Though I don't know the details of your system and don't really have the bandwidth to help with cuda issues (sorry 😢 ).
