### ISSUE TITLE
breaks in the middle

### ISSUE THREAD

**Issue by zarigata** [nateraw/stable-diffusion-videos#161]
```
  File "C:\Users\Zarigata\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Zarigata\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\Zarigata\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Zarigata\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

evetime at the middle of the run

**Comment by Atomic-Germ** [comment]
Can you give your environment? It looks like you're on python 3.8, which could have to do with it in some way. If you can, it's best to set up a python 3.10 environment using conda.

**Comment by zarigata** [comment]
i have upgraded and it kinda works, not with conda thought

**Comment by Atomic-Germ** [comment]
> i have upgraded and it kinda works, not with conda thought

Personally, I can't get anything torch related to work without conda.
