### ISSUE TITLE
Issue with Installation

### ISSUE THREAD

**Issue by morphogencc** [nateraw/stable-diffusion-videos#170]
I'm trying to install the repo via `pip`.  I'm running Python 3.8.0 and pip 23.0.1.

Just like on the homepage, I ran:

```
pip install -U stable_diffusion_videos
```
And had an issue installed `basicsr`:

```
Collecting basicsr>=1.3.3.11
  Using cached basicsr-1.4.2.tar.gz (172 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-install-c4a4ukdm\basicsr_23c1a64c152149be84c144fda2cae2ac\setup.py", line 147, in <module>
          setup(
        File "d:\apps\interactiveimpressions\env\lib\site-packages\setuptools\__init__.py", line 144, in setup
          _install_setup_requires(attrs)
        File "d:\apps\interactiveimpressions\env\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "d:\apps\interactiveimpressions\env\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "d:\apps\interactiveimpressions\env\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
          dist = best[req.key] = env.best_match(
        File "d:\apps\interactiveimpressions\env\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
          return self.obtain(req, installer)
        File "d:\apps\interactiveimpressions\env\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
          return installer(requirement)
        File "d:\apps\interactiveimpressions\env\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
          return cmd.easy_install(req)
        File "d:\apps\interactiveimpressions\env\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "d:\apps\interactiveimpressions\env\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "d:\apps\interactiveimpressions\env\lib\site-packages\setuptools\command\easy_install.py", line 855, in install_eggs
          return [self.install_wheel(dist_filename, tmpdir)]
        File "d:\apps\interactiveimpressions\env\lib\site-packages\setuptools\command\easy_install.py", line 1068, in install_wheel
          self.execute(
        File "C:\Python38\lib\distutils\cmd.py", line 335, in execute
          util.execute(func, args, msg, dry_run=self.dry_run)
        File "C:\Python38\lib\distutils\util.py", line 303, in execute
          func(*args)
        File "d:\apps\interactiveimpressions\env\lib\site-packages\setuptools\wheel.py", line 101, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "d:\apps\interactiveimpressions\env\lib\site-packages\setuptools\wheel.py", line 105, in _install_as_egg
          dist_info = self.get_dist_info(zf)
        File "d:\apps\interactiveimpressions\env\lib\site-packages\setuptools\wheel.py", line 96, in get_dist_info
          raise ValueError("unsupported wheel format. .dist-info not found")
      ValueError: unsupported wheel format. .dist-info not found
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

This doesn't necessarily look like an issue with this repo as much with a dependency, but does anyone have any suggestions for how to get past it?

**Comment by ndelib** [comment]
hey mate - I ran into this problem too. Fixed it by upgrading my version of pip (the python package installer) to version 23.1.2. I did so by running this command on Ubuntu 20.04: python3 -m pip install --upgrade pip. Hope that helps!

**Comment by nateraw** [comment]
Nice, thank you @ndelib! Anybody else who has/is running into this issue, can you try upgrading pip and see what happens?

If issues still occurring, please provide a way for me to reproduce the issue if you can :).

**Comment by dibg** [comment]
Issue still exists. 
My system is arch with pip-23.1.2 and python 3.11.5

**Comment by Anning01** [comment]
Try first:
`pip install --upgrade setuptools wheel`

If this still does not work, please execute the following command.
`pip install --use-pep517 basicsr`

Successful！
