### ISSUE TITLE
ModuleNotFoundError: No module named 'websockets.datastructures'

### ISSUE THREAD

**Issue by kritonpc** [nateraw/stable-diffusion-videos#2]
When I clone the repo to my pc and try to run it it pops the following error
```
>>> from app import interface
>>> interface.launch()
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\lib\site-packages\uvicorn\config.py", line 471, in load
    ws_protocol_class = import_from_string(WS_PROTOCOLS[self.ws])
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\lib\site-packages\uvicorn\protocols\websockets\auto.py", line 17, in <module>
    from uvicorn.protocols.websockets.websockets_impl import WebSocketProtocol
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 9, in <module>
    from websockets.datastructures import Headers
ModuleNotFoundError: No module named 'websockets.datastructures'

```

**Comment by kritonpc** [comment]
For anyone having the same issue pip install --upgrade websockets
