### ISSUE TITLE
Installation Error - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Mr-Anonymous** [nateraw/stable-diffusion-videos#204]
When I install using `pip install stable_diffusion_videos` in Macbook Pro, I get this error:

```
Collecting stable_diffusion_videos
  Using cached https://files.pythonhosted.org/packages/65/f3/adf3d1e7a71a7ff05f5338c89fb3b9c44e1159e7837e5db9a44feb489b32/stable_diffusion_videos-0.8.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/me/.pyenv/versions/2.7.18/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bd/ykzrnnxd0cddfmx6mkmk1_y40000gn/T/pip-install-wulxcp/stable-diffusion-videos/setup.py'"'"'; __file__='"'"'/private/var/folders/bd/ykzrnnxd0cddfmx6mkmk1_y40000gn/T/pip-install-wulxcp/stable-diffusion-videos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/bd/ykzrnnxd0cddfmx6mkmk1_y40000gn/T/pip-install-wulxcp/stable-diffusion-videos/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bd/ykzrnnxd0cddfmx6mkmk1_y40000gn/T/pip-install-wulxcp/stable-diffusion-videos/setup.py", line 4
        def get_version() -> str:
                          ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Mr-Anonymous** [comment]
I was able to install it using this command:

```
python3 -m pip install stable_diffusion_videos
```

I also updated Python and Pip.
