### ISSUE TITLE
Not sure what caused this issue. I can make images fine, but when it completes the videos, I get this message.

### ISSUE THREAD

**Issue by gsgoldma** [nateraw/stable-diffusion-videos#59]
This is from finishing the video interpolation in the local app interface

Traceback (most recent call last):
  File "D:\Python\lib\site-packages\gradio\routes.py", line 273, in run_predict
    output = await app.blocks.process_api(
  File "D:\Python\lib\site-packages\gradio\blocks.py", line 753, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "D:\Python\lib\site-packages\gradio\blocks.py", line 630, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Python\lib\site-packages\stable_diffusion_videos\app.py", line 57, in fn_videos
    video_path = walk(
  File "D:\Python\lib\site-packages\stable_diffusion_videos\stable_diffusion_walk.py", line 288, in walk
    return make_video_ffmpeg(output_path, f"{name}.mp4", fps=fps, frame_filename=f"frame%06d{frame_filename_ext}")
  File "D:\Python\lib\site-packages\stable_diffusion_videos\stable_diffusion_walk.py", line 66, in make_video_ffmpeg
    subprocess.call(
  File "D:\Python\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Python\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Python\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

This is from running it on command terminal after typing in python

from stable_diffusion_videos import walk
>>> walk(
...     prompts=['a cat', 'a dog'],
...     seeds=[42, 1337],
...     output_dir='dreams',     # Where images/videos will be saved
...     name='animals_test',     # Subdirectory of output_dir where images/videos will be saved
...     guidance_scale=8.5,      # Higher adheres to prompt more, lower lets model take the wheel
...     num_steps=5,             # Change to 60-200 for better results...3-5 for testing
...     num_inference_steps=50,
...     scheduler='klms',        # One of: "klms", "default", "ddim"
...     disable_tqdm=False,      # Set to True to disable tqdm progress bar
...     make_video=True,         # If false, just save images
...     use_lerp_for_text=True,  # Use lerp for text embeddings instead of slerp
...     do_loop=False,           # Change to True if you want last prompt to loop back to first prompt
... )
COUNT: 0/5
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:34<00:00,  1.45it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:36<00:00,  1.39it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:37<00:00,  1.35it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:37<00:00,  1.33it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:36<00:00,  1.36it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\lib\site-packages\stable_diffusion_videos\stable_diffusion_walk.py", line 288, in walk
    return make_video_ffmpeg(output_path, f"{name}.mp4", fps=fps, frame_filename=f"frame%06d{frame_filename_ext}")
  File "D:\Python\lib\site-packages\stable_diffusion_videos\stable_diffusion_walk.py", line 66, in make_video_ffmpeg
    subprocess.call(
  File "D:\Python\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Python\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Python\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by gsgoldma** [comment]
I got it to word; had to install ffmpeg and add it to path.
at some point I changed shell=true in subprocess.py, which changed the error message to ffmpeg not found, but when I went to change it back to false it was already set to true again. But the ffmpeg solved the issue.

**Comment by nateraw** [comment]
Duplicate of #50 - still no solution here. will likely reopen that one before fixing
